### ISSUE TITLE
问一个低级的问题

### ISSUE THREAD

**Issue by Liare** [elmorec/hexo-theme-inside#17]
在本地目录下新建了tags和categories目录之后，这两个目录的内容怎么显示。。。我的tags和categories这两个网页目录里面都是空的。。新手求教，。很喜欢这个主题不想再换了。。

**Comment by elmorec** [comment]
不需要建目录呀，标签和目录这样加：
```yaml
---
title: 标题
date: 2018-06-11
tags:
 - 标签1
 - 标签2
categories:
 - 分类1
 - 分类2
---
```
见hexo官方文档 [front-matter](https://hexo.io/docs/front-matter.html)。
